name = "apollocacheupdater"
main = "worker.js"
compatibility_date = "2025-01-17"
preview_urls = false
send_metrics = false
workers_dev = true

services = [
    {binding = "GALLERY", service = "apollogallery"}
]

[triggers]
crons = ["0 4 * * *"]

[[kv_namespaces]]
binding = "CACHE_KV"
id = "ec290df347654a639feecda9c0b077c4"

