name = "apollocacheupdater"
main = "worker.js"
compatibility_date = "2025-01-17"
preview_urls = false
send_metrics = false
workers_dev = false

services = [
  { binding = "LOGGER", service = "workerlogstodiscord" }
]

[triggers]
crons = ["0 0 * * *"]

[[kv_namespaces]]
binding = "CACHE_KV"
id = "ec290df347654a639feecda9c0b077c4"

[vars]
# The hostname that we should update, it ideally would use the CF pages binding, but that doesn't seem to work.
GALLERY_HOSTNAME = "apollo.dog"

# if log forwarding should be used
USE_LOG_FORWARDER = "true"
# worker name (used for logging)
WORKER_NAME = "Apollo Gallery Refresher"